services:
  api:
    depends_on:
      postgres-database:
        condition: service_healthy
    links:
      - postgres-database
    build:
      context: .
      dockerfile: Sobczal.InPost.Api/Dockerfile
    ports:
      - 8081:80

  client:
    depends_on:
      postgres-database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Sobczal.InPost.Client/Dockerfile
    ports:
      - 8080:80

  postgres-database:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '15432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
